### ISSUE TITLE
Create a student controller for a School Management System. Implement CRUD operations (Create, Read, Update, Delete) for student 

### ISSUE THREAD

**Issue by AbdullahElamir** [QualityAssuranceProfessional/students-management-backend#5]
Create a student controller for a School Management System. Implement CRUD operations (Create, Read, Update, Delete) for student records. Table properties include: StudentId, Photo, FirstName, FahterName, GrandFatherName, SurName, Gender, NationalId, BirthDate, JoinDate, BloodType, YearClassID, Username, Email, Password, RegionId, Address, ParentName, ParentPhone, ParentEmail, CreatedOn, CreatedBy, and Status.

**Comment by EnassGashout** [comment]
Done
